version: '3.8'

services:
  sample-website:
    image: ghcr.io/rs223483/sample-website:latest
    container_name: sample-website
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./logs:/var/log/nginx
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - app-network
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  app-network:
    driver: bridge

volumes:
  logs:
    driver: local
